kind: ConfigMap
apiVersion: v1
metadata:
  name: load-test-config
  namespace: {{ .Env.NAMESPACE }}
data:
  tenant: 1C927CAC-1163-4649-A36D-DCE4F47C7C5A
  scheme: http
  read_hostname: thanos-query-frontend.{{ .Env.NAMESPACE }}.svc.cluster.local:9090
  write_hostname: thanos-receive-default.{{ .Env.NAMESPACE }}.svc.cluster.local:19291
  read_request_rate: '1'
  # The number of remote write requests to perform per scrape interval.
  # This is multiplied by ha_clusters
  # rps is therefore calculated as (write_request_rate / scrape_interval) * ha_clusters
  write_request_rate: '10000'
  scrape_interval_seconds: '30'
  # Number of series per remote write request.
  write_series_per_request: '3000' # Active series can be calculated by (write_series_per_request * write_request_rate)
  ha_clusters: '1'
  ha_replicas: '1' # Each time series will be sent this number of times
  duration_minutes: '50'
  ramp_up_minutes: '20'
  ramp_down_minutes: '0'
  run-identifier: '10-million-active-series-30s-1-write-queue-enabled'
  remote_write_url: http://thanos-receive-default.{{ .Env.NAMESPACE }}.svc.cluster.local:19291/api/v1/receive
  query_url: http://thanos-query-frontend.{{ .Env.NAMESPACE }}.svc.cluster.local:9090/api/v1

