apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: {{ .Env.NAMESPACE }}
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: thanos
      endpoint: minio.{{ .Env.NAMESPACE }}.svc.cluster.local:9000
      insecure: true
      access_key: minio
      secret_key: minio123
type: Opaque
