apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: {{ .Env.NAMESPACE }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          mkdir -p /storage/thanos && \
          /usr/bin/docker-entrypoint.sh minio server /storage
        env:
        - name: MINIO_ROOT_USER
          value: minio
        - name: MINIO_ROOT_PASSWORD
          value: minio123
        image: {{ .Env.MINIO_IMG }} 
        imagePullPolicy: IfNotPresent
        name: minio
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /storage
          name: storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minio
