apiVersion: v1
data:
  queries.yaml: |-
    "queries":
    - "name": "10000 series per block one week"
      "query": "sum(continuous_app_metric0) by (cluster, replica)"
      "duration": "2w"
      "cache": false
    "series":
    - "name": "10000 series per block one week"
      "matchers": 
      - "continuous_app_metric0"
      "duration": "2w"
      "cache": false
    "labels":
    - "name": "All unique labels"
      "label": "__blockgen_target__"
      "duration": "2w"
      "cache": false
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: blackbox-prober
    app.kubernetes.io/instance: thanos-bench
    app.kubernetes.io/name: up
    app.kubernetes.io/part-of: thanos-bench
  name: up
  namespace: {{ .Env.NAMESPACE }}
