apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: blackbox-prober
    app.kubernetes.io/instance: thanos-bench
    app.kubernetes.io/name: up
    app.kubernetes.io/part-of: thanos-bench
  name: up
  namespace: {{ .Env.NAMESPACE }}
spec:
  replicas: {{ .Env.UP_REPLICAS }}
  selector:
    matchLabels:
      app.kubernetes.io/component: blackbox-prober
      app.kubernetes.io/instance: thanos-bench
      app.kubernetes.io/name: up
      app.kubernetes.io/part-of: thanos-bench
  template:
    metadata:
      labels:
        app.kubernetes.io/component: blackbox-prober
        app.kubernetes.io/instance: thanos-bench
        app.kubernetes.io/name: up
        app.kubernetes.io/part-of: thanos-bench
    spec:
      containers:
        - args:
            - --duration=0
            - --log.level=debug
            - --endpoint-type=metrics
            - --queries-file=/etc/up/queries.yaml
            - --endpoint-read=http://thanos-query-frontend.{{ .Env.NAMESPACE }}.svc.cluster.local:9090
          image: quay.io/observatorium/up:master-2022-03-24-098c31a
          name: up
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /etc/up/
              name: query-config
              readOnly: false
      volumes:
        - configMap:
            name: up
          name: query-config
