apiVersion: v1
imagePullSecrets:
  - name: quay.io
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: store-index-cache
    app.kubernetes.io/instance: thanos-bench
    app.kubernetes.io/name: memcached
    app.kubernetes.io/part-of: thanos-bench
  name: thanos-store-index-cache-memcached
  namespace: {{ .Env.NAMESPACE }}