apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: store-bucket-cache
    app.kubernetes.io/instance: thanos-bench
    app.kubernetes.io/name: memcached
    app.kubernetes.io/part-of: thanos-bench
  name: thanos-store-bucket-cache-memcached
  namespace: {{ .Env.NAMESPACE }}
spec:
  clusterIP: None
  ports:
    - name: client
      port: 11211
      targetPort: 11211
    - name: metrics
      port: 9150
      targetPort: 9150
  selector:
    app.kubernetes.io/component: store-bucket-cache
    app.kubernetes.io/instance: thanos-bench
    app.kubernetes.io/name: memcached
    app.kubernetes.io/part-of: thanos-bench