apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: avalanche
    app.kubernetes.io/name: avalanche-remote-writer
    app.kubernetes.io/part-of: thanos-bench
  name: avalanche-remote-writer
  namespace: {{ .Env.NAMESPACE }}
spec:
  replicas: {{ .Env.AVALANCHE_REPLICAS }}
  selector:
    matchLabels:
      app.kubernetes.io/component: avalanche
      app.kubernetes.io/name: avalanche-remote-writer
      app.kubernetes.io/part-of: thanos-bench
  template:
    metadata:
      labels:
        app.kubernetes.io/component: avalanche
        app.kubernetes.io/name: avalanche-remote-writer
        app.kubernetes.io/part-of: thanos-bench
    spec:
      containers:
        - args:
            - --metric-count={{ .Env.METRIC_COUNT }}
            - --series-count={{ .Env.SERIES_COUNT }}
            - --label-count={{ .Env.LABEL_COUNT }}
            - --remote-url=http://thanos-receive-default.{{ .Env.NAMESPACE }}.svc.cluster.local:19291/api/v1/receive
            - --value-interval={{ .Env.VALUE_INTERVAL }}
            - --series-interval={{ .Env.SERIES_INTERVAL }}
            - --metric-interval={{ .Env.METRIC_INTERVAL }}
            - --remote-requests-count={{ .Env.REMOTE_REQUESTS_COUNT }}
            - --remote-write-interval={{ .Env.REMOTE_WRITE_INTERVAL }}
            - --remote-tenant-header={{ .Env.REMOTE_TENANT_HEADER }}
            - --remote-tenant={{ .Env.REMOTE_TENANT }}            
          image: {{ .Env.AVALANCHE_IMG }}
          name: avalanche-remote-writer
