apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: thanos-receive-default
  namespace: {{ .Env.NAMESPACE }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: database-write-hashring
      app.kubernetes.io/instance: thanos-bench
      app.kubernetes.io/name: thanos-receive
      app.kubernetes.io/part-of: thanos-bench
      controller.receive.thanos.io/hashring: default
