apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: query-range-cache
    app.kubernetes.io/instance: thanos-bench
    app.kubernetes.io/name: memcached
    app.kubernetes.io/part-of: thanos-bench
  name: thanos-query-range-cache-memcached
  namespace: {{ .Env.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: query-range-cache
      app.kubernetes.io/instance: thanos-bench
      app.kubernetes.io/name: memcached
      app.kubernetes.io/part-of: thanos-bench
  serviceName: thanos-query-range-cache-memcached
  template:
    metadata:
      labels:
        app.kubernetes.io/component: query-range-cache
        app.kubernetes.io/instance: thanos-bench
        app.kubernetes.io/name: memcached
        app.kubernetes.io/part-of: thanos-bench
    spec:
      containers:
        - args:
            - -m {{ .Env.THANOS_QUERY_FRONTEND_QUERY_CACHE_MEMORY_LIMIT_MB }}
            - -I 64m
            - -c {{ .Env.THANOS_QUERY_FRONTEND_QUERY_CACHE_CONNECTION_LIMIT }}
            - -v
          image: {{ .Env.MEMCACHED_IMG }}
          imagePullPolicy: IfNotPresent
          name: memcached
          ports:
            - containerPort: 11211
              name: client
          resources:
            requests:
              cpu: {{ .Env.THANOS_QUERY_FRONTEND_QUERY_CACHE_MEMCACHED_CPU_REQUEST }}
              memory: {{ .Env.THANOS_QUERY_FRONTEND_QUERY_CACHE_MEMCACHED_MEMORY_REQUEST }}
          terminationMessagePolicy: FallbackToLogsOnError
        - args:
            - --memcached.address=localhost:11211
            - --web.listen-address=0.0.0.0:9150
          image: {{ .Env.MEMCACHED_EXPORTER_IMG }}
          imagePullPolicy: IfNotPresent
          name: exporter
          ports:
            - containerPort: 9150
              name: metrics
          resources:
            requests:
              cpu: {{ .Env.MEMCACHED_EXPORTER_CPU_REQUEST }}
              memory: {{ .Env.MEMCACHED_EXPORTER_MEMORY_REQUEST }}
      securityContext: {}
      serviceAccountName: thanos-query-range-cache-memcached