apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: kubernetes-controller
    app.kubernetes.io/instance: thanos-bench
    app.kubernetes.io/name: thanos-receive-controller
    app.kubernetes.io/part-of: thanos-bench
  name: thanos-receive-controller
  namespace: {{ .Env.NAMESPACE }}