apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: database-write-hashring
    app.kubernetes.io/instance: thanos-bench
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/part-of: thanos-bench
  name: thanos-receive
  namespace: {{ .Env.NAMESPACE }}
