  apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app.kubernetes.io/component: kubernetes-controller
      app.kubernetes.io/instance: thanos-bench
      app.kubernetes.io/name: thanos-receive-controller
      app.kubernetes.io/part-of: thanos-bench
    name: thanos-receive-controller
    namespace: {{ .Env.NAMESPACE }}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/component: kubernetes-controller
        app.kubernetes.io/instance: thanos-bench
        app.kubernetes.io/name: thanos-receive-controller
        app.kubernetes.io/part-of: thanos-bench
    template:
      metadata:
        labels:
          app.kubernetes.io/component: kubernetes-controller
          app.kubernetes.io/instance: thanos-bench
          app.kubernetes.io/name: thanos-receive-controller
          app.kubernetes.io/part-of: thanos-bench
      spec:
        containers:
        - args:
          - --configmap-name=thanos-receive-controller-tenants
          - --configmap-generated-name=thanos-receive-controller-tenants-generated
          - --file-name=hashrings.json
          - --namespace=$(NAMESPACE)
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: {{ .Env.HASHRING_CONTROLLER_IMG }}
          imagePullPolicy: IfNotPresent
          name: thanos-receive-controller
          ports:
          - containerPort: 8080
            name: http
          resources:
            requests:
              cpu: 10m
              memory: 24Mi
          securityContext: {}
        securityContext: {}
        serviceAccount: thanos-receive-controller